name: JumpPads
author: Lev_112233 
main: me.Main
softdepend: [HolographicDisplays]
version: "1.0"

commands:
  jumppads:
    aliases: [jumppad]
    permission: op
    description: Jump Pads Command
